spring.application.name=demo
#spring.kafka.bootstrap-servers=kafka-server:9092
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=springboot_kafkabridge
spring.kafka.consumer.auto-offset-reset=earliest

spring.mongodb.uri=mongodb://admin:password123@localhost:27017/kafka_dump?authSource=admin
#spring.mongodb.uri=mongodb://admin:password123@mongo-server:27017/kafka_dump?authSource=admin

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.kafkabridge.demo.model.UserDetails
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.kafkabridge.demo.model